FROM node:22-alpine
WORKDIR /app/frontend
COPY app/frontend/package.json app/frontend/package-lock.json ./
RUN npm ci
COPY app/frontend/docker-entrypoint.sh ./
RUN chmod +x docker-entrypoint.sh
EXPOSE 4321
CMD ["/bin/sh","./docker-entrypoint.sh"]
