FROM node:22-alpine
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
EXPOSE 4321
ARG PUBLIC_API_URL
ENV PUBLIC_API_URL=$PUBLIC_API_URL
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
