FROM node:22-alpine
RUN apk add --no-cache bash tmux
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
ENV HOST=0.0.0.0
CMD ["node", "--watch", "--experimental-strip-types", "index.ts"]
