FROM node:22-alpine
WORKDIR /app/api
COPY app/api/package.json app/api/package-lock.json ./
RUN npm ci
COPY app/api/docker-entrypoint.sh ./
RUN chmod +x docker-entrypoint.sh
CMD ["/bin/sh","./docker-entrypoint.sh"]
